version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11-browsers
    steps:
      - checkout
      - restore_cache:
          key: -v3-{{ checksum "package.json" }}
      - run: 
          name: Yarn
          command: |
            yarn
      - run:
          name: Test
          command: |
            yarn test
      - run:
          name: Codecov
          command: |
            ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
            ./node_modules/.bin/codecov -t 4a7a492a-fc7a-426d-9e9a-64aa9f3f41cb
      - save_cache:
          key: -v3-{{ checksum "package.json" }}
          paths:
            - "yarn.lock"
            - "node_modules"
workflows:
  version: 2
  tests:
    jobs:
      - test
